import 'package:get/get.dart';

class TranslationFilePage extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'Home': 'Home',
          'Discussion': 'Discussion',
          'Listings': 'Listings',
          'Message': 'Message',
          'Government': 'Government',
          "Can't get gurrent location": "Can't get gurrent location",
          'Please make sure you enable GPS and try again':
              'Please make sure you enable GPS and try again',
          'Ok': 'Ok',
          'Alert': 'Alert',
          'Success': 'Success',
          'my-widget-key': 'my-widget-key',
          'Advertise': 'Advertise',
          'For': 'For',
          'Advertising': 'Advertising',
          'kindly contact us for further information ':
              'kindly contact us for further information ',
          'advertise@dailboxx.pk': 'advertise@dailboxx.pk',
          'Notifications': 'Notifications',
          'PP': 'PP',
          'We\'re never more than 5 minutes away with pick-up stations closer from and to your home, office or anywhere in between.':
              'We\'re never more than 5 minutes away with pick-up stations closer from and to your home, office or anywhere in between.',
          '15 June at 02:05 am': '15 June at 02:05 am',
          'Settings': 'Settings',
          'Change Password': 'Change Password',
          'Terms & Conditions': 'Terms & Conditions',
          'Privacy Policy': 'Privacy Policy',
          'Version': 'Version',
          '1.0.0': '1.0.0',
          'Skip': 'Skip',
          'Let\'s do your new habit': 'Let\'s do your new habit',
          'Verification Code': 'Verification Code',
          'Register your bussiness with dialboxx to gain visibility in the marketplace.':
              'Register your bussiness with dialboxx to gain visibility in the marketplace.',
          'NEXT': 'NEXT',
          'SIGN UP AS': 'SIGN UP AS',
          'Register your bussiness with dialboxx to gain visibility in the marketplace. Showcase your bussiness information.':
              'Register your bussiness with dialboxx to gain visibility in the marketplace. Showcase your bussiness information.',
          'BUSSINES OWNER': 'BUSSINES OWNER',
          'USER': 'USER',
          'Add Business': 'Add Business',
          'Register your bussiness with dialbox to gain visibility in the marketplace. Showcase your bussiness information, products + Services helping you increase your revenue by bringing you closer to your potential clients.':
              'Register your bussiness with dialbox to gain visibility in the marketplace. Showcase your bussiness information, products + Services helping you increase your revenue by bringing you closer to your potential clients.',
          'Choose your plan today and \n1st MONTH FREE':
              'Choose your plan today and \n1st MONTH FREE',
          'Basic Package': 'Basic Package',
          '1,000': '1,000',
          'PKR': 'PKR',
          'Per Month': 'Per Month',
          '2,500 PKR': '2,500 PKR',
          'Annual Package': 'Annual Package',
          '24,000': '24,000',
          '30,000 PKR': '30,000 PKR',
          'Gold Package': 'Gold Package',
          '25,000': '25,000',
          '33,000 PKR': '33,000 PKR',
          'PLANS Benefits': 'PLANS Benefits',
          'Basic Pakage': 'Basic Pakage',
          'We\'re never more than 5 minutes away with pick-up stations closer from and to your home, office or anywhere in between. Grabbing coffee along your way? Grabbing coffee along your way? Grabbing coffee along your way?': 'We\'re never more than 5 minutes away with pick-up stations closer from and to your home, office or anywhere in between. Grabbing coffee along your way? Grabbing coffee along your way? Grabbing coffee along your way?',
          'Annual Pakage': 'Annual Pakage',
          'Gold Pakage': 'Gold Pakage',
          'Add Product': 'Add Product',
          'Service Name': 'Service Name',
          'Service Cost': 'Service Cost',
          'Service Details': 'Service Details',
          'Select Business': 'Select Business',
          'Add Service': 'Add Service',
          'Product Name': 'Product Name',
          'Product Price': 'Product Price',
          'Product Details': 'Product Details',
          'Product image 1': 'Product image 1',
          'Product image 2': 'Product image 2',
          'Product image 3': 'Product image 3',
          'Discussion Forum': 'Discussion Forum',
          'Search here': 'Search here',
          'Add new Discussion Post': 'Add new Discussion Post',
          'Write something here': 'Write something here',
          'Add Pictures': 'Add Pictures',
          'Select Industry': 'Select Industry',
          'Category': 'Category',
          'Business': 'Business',
          'Publish Now': 'Publish Now',
          'Empty': 'Empty',
          'Edit': 'Edit',
          'Delete': 'Delete',
          'See more': 'See more',
          'See less': 'See less',
          'Comments': 'Comments',
          'Camera': 'Camera',
          'Gallary': 'Gallary',
          'Government Directory': 'Government Directory',
          'Business Name': 'Business Name',
          'Contact info': 'Contact info',
          'Business Overview': 'Business Overview',
          'Business Offered': 'Business Offered',
          'Contact': 'Contact',
          'Search service or industry': 'Search service or industry',
          'Most Popular Industries': 'Most Popular Industries',
          'View All ': 'View All ',
          'Whats Trending Now?': 'Whats Trending Now?',
          'Most Recent Listings': 'Most Recent Listings',
          'Popular Product': 'Popular Product',
          'Popular Services': 'Popular Services',
          'product': 'product',
          'service': 'service',
          'data': 'data',
          'RMS Pack & Movers Service': 'RMS Pack & Movers Service',
          'blue area islamabad': 'blue area islamabad',
          '125 reviews': '125 reviews',
          'Call': 'Call',
          'Chat': 'Chat',
          'Business name*': 'Business name*',
          'Business Description*': 'Business Description*',
          'Business email': 'Business email',
          'Cell number': 'Cell number',
          'Landline number': 'Landline number',
          'WhatsApp number': 'WhatsApp number',
          'City': 'City',
          'Physical store* / Virtual store*': 'Physical store* / Virtual store*',
          'Timings': 'Timings',
          'Monday ': 'Monday ',
          'Tuesday ': 'Tuesday ',
          'Wednesday ': 'Wednesday ',
          'Thursday ': 'Thursday ',
          'Friday ': 'Friday ',
          'Saturday ': 'Saturday ',
          'Sunday ': 'Sunday ',
          'keywords': 'keywords',
          'Hear About': 'Hear About',
          'Select Image': 'Select Image',
          'SUBMIT': 'SUBMIT',
          'City* / Area**': 'City* / Area**',
          'Website URL': 'Website URL',
          'Number of Employs': 'Number of Employs',
          'FaceBook URL': 'FaceBook URL',
          'Instagram URL': 'Instagram URL',
          'Twitter URL': 'Twitter URL',
          'Youtube URl': 'Youtube URl',
          'Service Area': 'Service Area',
          'Delivery Available': 'Delivery Available',
          'PickUp': 'PickUp',
          'By Appointment': 'By Appointment',
          'Business Registration': 'Business Registration',
          'Create your': 'Create your',
          ' Business ': ' Business ',
          'Account free and get Register your business': 'Account free and get Register your business',
          'salc': 'salc',
          'Select Package': 'Select Package',
          'Yes': 'Yes',
          'No': 'No',
          'Booking': 'Booking',
          'Sub Category': 'Sub Category',
          'Select time': 'Select time',
          'Contact Us': 'Contact Us',
          'Call Us': 'Call Us',
          'Email Us': 'Email Us',
          'Chat with Us': 'Chat with Us',
          'Quick Contact': 'Quick Contact',
          'First Name': 'First Name',
          'Email': 'Email',
          'Phone': 'Phone',
          'SEND': 'SEND',
          'Confirm': 'Confirm',
          ' your ': ' your ',
          'password ': 'password ',
          'Let\'s finally..': 'Let\'s finally..',
          'New Password': 'New Password',
          'Confirm Password': 'Confirm Password',
          'OTP': 'OTP',
          'Forgot': 'Forgot',
          'so Try again..': 'so Try again..',
          'Add New Business': 'Add New Business',
          'Profile': 'Profile',
          'How it works': 'How it works',
          'Customer care': 'Customer care',
          'Logout': 'Logout',
          'How it Works': 'How it Works',
          'Filter': 'Filter',
          'Verified': 'Verified',
          'Open Now': 'Open Now',
          'Top Rated': 'Top Rated',
          'Send Message': 'Send Message',
          'Enter message here': 'Enter message here',
          '3.30PM': '3.30PM',
          'Say something …': 'Say something …',
          'Phone verification': 'Phone verification',
          'Otp code': 'Otp code',
          'Arrive at your destination in the smoothest ride possible, by sailing through real-time trip planning to payment with a few clicks. We\'re never more than 5 minutes away with pick-up stations closer from and to your home, office or anywhere in between. Grabbing coffee along your way?': 'Arrive at your destination in the smoothest ride possible, by sailing through real-time trip planning to payment with a few clicks. We\'re never more than 5 minutes away with pick-up stations closer from and to your home, office or anywhere in between. Grabbing coffee along your way?',
          '': '',
          '': '',
          '': '',
          '': '',
          '': '',
          '': '',
          '': '',
          '': '',
          '': '',
          '': '',
          '': '',
          '': '',
          '': '',
          '': '',
          '': '',
          '': '',
          '': '',
          '': '',
          '': '',
          '': '',
          '': '',
          '': '',
          '': '',
        },

        //...................................................//
        'de_DE': {
          'hello': 'Hallo Welt',
        }
      };
}
