import 'package:get/get.dart';

class TranslationFilePage extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'Home': 'Home',
          'Discussion': 'Discussion',
          'Please confirm Terms and Condition':
              'Please confirm Terms and Condition',
          'Add': 'Add',
          'Monday :': 'Monday :',
          'Wednesday :': 'Wednesday :',
          'Rate Service': 'Rate Service',
          'Business Address*': 'Business Address*',
          ' business ': ' business ',
          'Facebook Link': 'Facebook Link',
          'Photos': 'Photos',
          'New Password': 'New Password',
          'Add FAQs': 'Add FAQs',
          'Thursday:': 'Thursday:',
          'YouTube Link': 'YouTube Link',
          'My Listings': 'My Listings',
          'Upload Picture': 'Upload Picture',
          ' Privacy Policy': ' Privacy Policy',
          'Please enter first name': 'Please enter first name',
          'Please enter last name': 'Please enter last name',
          'Password didn\'t match': 'Password didn\'t match',
          'Send Report': 'Send Report',
          'You can start listing your businesses after\n registration.':
              'You can start listing your businesses after\n registration.',
          'Rate your experience': 'Rate your experience',
          'for FREE today': 'for FREE today',
          'City :': 'City :',
          'Categories': 'Categories',
          'Donʼt have an account ? ': 'Donʼt have an account ? ',
          'Rate your Experience here': 'Rate your Experience here',
          'Rate Product': 'Rate Product',
          'Terms ': 'Terms ',
          'Activities': 'Activities',
          'Information': 'Information',
          'Rating & Reviews': 'Rating & Reviews',
          'View Business': 'View Business',
          'Update Education': 'Update Education',
          'Write your skills here': 'Write your skills here',
          'Update Experience': 'Update Experience',
          'Write your Education here': 'Write your Education here',
          'Business City(s) : ': 'Business City(s) : ',
          'Update Skills': 'Update Skills',
          'I agree to Dialboxx Terms & Conditions':
              'I agree to Dialboxx Terms & Conditions',
          'Please enter feed back': 'Please enter feed back',
          'Please rate to Driver': 'Please rate to Driver',
          'FAQs': 'FAQs',
          'Business Details': 'Business Details',
          'Write your School name': 'Write your School name',
          'All Likes': 'All Likes',
          'Monday - Sunday': 'Monday - Sunday',
          'Time Duration': 'Time Duration',
          'Write your company name': 'Write your company name',
          'Write your position here': 'Write your position here',
          'Add accomplishments': 'Add accomplishments',
          'Add Education': 'Add Education',
          'Experience': 'Experience',
          'Update accomplishments': 'Update accomplishments',
          'Mobile No*': 'Mobile No*',
          'Write your Volunteering here': 'Write your Volunteering here',
          'Update Volunteering': 'Update Volunteering',
          'Add Volunteering': 'Add Volunteering',
          'Report': 'Report',
          'Write your accomplishments here': 'Write your accomplishments here',
          'Get in touch': 'Get in touch',
          'It’s okay to be tired. Try to take some deep breaths when you have a quick minute to yourself. Remember you are worth it! Being kind to others is just as important as being kind to yourself. ':
              'It’s okay to be tired. Try to take some deep breaths when you have a quick minute to yourself. Remember you are worth it! Being kind to others is just as important as being kind to yourself. ',
          'Packages': 'Packages',
          'Friday :': 'Friday :',
          'Saturday :': 'Saturday :',
          'Sunday :': 'Sunday :',
          'Education': 'Education',
          'Website link': 'Website link',
          'Volunteering': 'Volunteering',
          'Hello brother': 'Hello brother',
          'Please enter otp code': 'Please enter otp code',
          'Verify your account by entering 4 digit code you receive from Dialboxx':
              'Verify your account by entering 4 digit code you receive from Dialboxx',
          ' to connect with likeminded people in our community.':
              ' to connect with like minded people in our community.',
          'Submit': 'Submit',
          'Hey! How’s it all going?': 'Hey! How’s it all going?',
          'Register your business with Dialboxx to gain visibility in the market-place.Showcase your business information products + service .... ':
              'Register your business with Dialboxx to gain visibility in the market-place.Showcase your business information products + service .... ',
          'INDUSTRY': 'INDUSTRY',
          'Feeling quite overwhelmed today. Wish I had more time to myself.':
              'Feeling quite overwhelmed today. Wish I had more time to myself.',
          'It’s been an okay day… Lots of School work':
              'It’s been an okay day… Lots of School work',
          ' on Dialboxx to gain leads and to showcase your products, services & business information online.':
              ' on Dialboxx to gain leads and to showcase your products, services & business information online.',
          'List your business': 'List your business',
          'Categories > business': 'Categories > business',
          'CATEGORIES': 'CATEGORIES',
          'Service Areas': 'Service Areas',
          'Please add your questions': 'Please add your questions',
          'Enter your email or number below and we will send you a link to reset your password.':
              'Enter your email or number below and we will send you a link to reset your password.',
          'Listings': 'Listings',
          'Fill in the': 'Fill in the',
          'Instagram Link': 'Instagram Link',
          'Add Experience': 'Add Experience',
          'Write your degree type': 'Write your degree type',
          'Hi , there ': 'Hi , there ',
          'Use Db discussion forum ': 'Use Db discussion forum ',
          'Search for anything, anywhere in Pakistan.':
              'Search for anything, anywhere in Pakistan.',
          'Please add your questions first': 'Please add your questions first',
          'Please type message to receiver': 'Please type message to receiver',
          'Select package first': 'Select package first',
          'Select how did you hear about us?':
              'Select how did you hear about us?',
          'Select City first': 'Select City first',
          'Select City': 'Select City',
          'Please fields should not is empty':
              'Please fields should not is empty',
          'Delivery Available*': 'Delivery Available*',
          'Register your business with dialboxx to gain visibility in the marketplace.':
              'Register your business with dialboxx to gain visibility in the marketplace.',
          'View All ': 'View All ',
          'Tuesday :': 'Tuesday :',
          'Please select image': 'Please select image',
          'Please enter message': 'Please enter message',
          'Add business name first': 'Add business name first',
          'Select Physical store* / Virtual store* first':
              'Select Physical store* / Virtual store* first',
          'Industries': 'Industries',
          'Number verification': 'Number verification',
          'Business Industry': 'Business Industry',
          'Skills': 'Skills',
          'Please enter password first': 'Please enter password first',
          'Update Business': 'Update Business',
          'Physical Location/Virtual*': 'Physical Location/Virtual*',
          'Urdu': 'Urdu',
          'Select Industry first': 'Select Industry first',
          'Please enter text': 'Please enter text',
          'Add cell number first': 'Add cell number first',
          'Search for service, product or business':
              'Search for service, product or business',
          'Update Product': 'Update Product',
          'Please select Category': 'Please select Category',
          'Create Account': 'Create Account',
          'Please select industry': 'Please select industry',
          'Update': 'Update',
          'Please select service first': 'Please select service first',
          'Please select minimum one image first':
              'Please select minimum one image first',
          'Message': 'Message',
          'Please enter phone number first': 'Please enter phone number first',
          'Recent Listings': 'Recent Listings',
          'Package Benefits': 'Package Benefits',
          'Please select city first': 'Please select city first',
          'Your account has been suspended . Please contact customer support':
              'Your account has been suspended . Please contact customer support',
          'Government': 'Government',
          'Service has been added Successfully':
              'Service has been added Successfully',
          'Accomplishments': 'Accomplishments',
          'Report has been submitted': 'Report has been submitted',
          "Can't get gurrent location": "Can't get gurrent location",
          'Please make sure you enable GPS and try again':
              'Please make sure you enable GPS and try again',
          'Ok': 'Ok',
          'Alert': 'Alert',
          'Select business address first': 'Select business address first',
          'Your listing has been sent for review. You will be notified once approved & online!':
              'Your listing has been sent for review. You will be notified once approved & online!',
          'Please verify your account': 'Please verify your account',
          'Success': 'Success',
          'my-widget-key': 'my-widget-key',
          'Advertise': 'Advertise',
          'Add Skills': 'Add Skills',
          'Please select product price first':
              'Please select product price first',
          'For': 'For',
          'Otp fields should not is empty': 'Otp fields should not is empty',
          'Advertising': 'Advertising',
          'kindly contact us for further information ':
              'kindly contact us for further information ',
          'advertise@dailboxx.pk': 'advertise@dailboxx.pk',
          'Notifications': 'Notifications',
          'PP': 'PP',
          'View Details': 'View Details',
          'We\'re never more than 5 minutes away with pick-up stations closer from and to your home, office or anywhere in between.':
              'We\'re never more than 5 minutes away with pick-up stations closer from and to your home, office or anywhere in between.',
          '15 June at 02:05 am': '15 June at 02:05 am',
          'Settings': 'Settings',
          'Change Password': 'Change Password',
          'Terms & Conditions': 'Terms & Conditions',
          'Privacy Policy': 'Privacy Policy',
          'Version': 'Version',
          '1.0.0': '1.0.0',
          'Take Away/Pick up': 'Take Away/Pick up',
          'Business Cell Number*': 'Business Cell Number*',
          'Skip': 'Skip',
          'Booking Available*': 'Booking Available*',
          'Let\'s do your new habit': 'Let\'s do your new habit',
          'Verification Code': 'Verification Code',
          'Register your bussiness with dialboxx to gain visibility in the marketplace.':
              'Register your bussiness with dialboxx to gain visibility in the marketplace.',
          'NEXT': 'NEXT',
          'SIGN UP AS': 'SIGN UP AS',
          'Register your bussiness with dialboxx to gain visibility in the marketplace. Showcase your bussiness information.':
              'Register your bussiness with dialboxx to gain visibility in the marketplace. Showcase your bussiness information.',
          'BUSSINES OWNER': 'BUSSINES OWNER',
          'USER': 'USER',
          'Add Business': 'Add Business',
          'Register your bussiness with dialbox to gain visibility in the marketplace. Showcase your bussiness information, products + Services helping you increase your revenue by bringing you closer to your potential clients.':
              'Register your bussiness with dialbox to gain visibility in the marketplace. Showcase your bussiness information, products + Services helping you increase your revenue by bringing you closer to your potential clients.',
          'Choose your plan today and \n1st MONTH FREE':
              'Choose your plan today and \n1st MONTH FREE',
          'Basic Package': 'Basic Package',
          '1,000': '1,000',
          'Question?': 'Question?',
          'PKR': 'PKR',
          'Department Overview': 'Department Overview',
          'Per Month': 'Per Month',
          'Write your time duration': 'Write your time duration',
          '2,500 PKR': '2,500 PKR',
          'Register your business with dialboxx and go online today! Help potential buyers get in touch with you using Dialboxx search engine.':
              'Register your business with dialboxx and go online today! Help potential buyers get in touch with you using Dialboxx search engine.',
          'Annual Package': 'Annual Package',
          '24,000': '24,000',
          'Type your answer here': 'Type your answer here',
          '30,000 PKR': '30,000 PKR',
          'Please select product name first':
              'Please select product name first',
          'Gold Package': 'Gold Package',
          '25,000': '25,000',
          'All Comments': 'All Comments',
          'Select Delivery Available first': 'Select Delivery Available first',
          '33,000 PKR': '33,000 PKR',
          'Please enter email or password': 'Please enter email or password',
          'PLANS Benefits': 'PLANS Benefits',
          'form and submit listing. Once approved, you can start listing products & services.':
              'form and submit listing. Once approved, you can start listing products & services.',
          'Basic Pakage': 'Basic Pakage',
          'We\'re never more than 5 minutes away with pick-up stations closer from and to your home, office or anywhere in between. Grabbing coffee along your way? Grabbing coffee along your way? Grabbing coffee along your way?':
              'We\'re never more than 5 minutes away with pick-up stations closer from and to your home, office or anywhere in between. Grabbing coffee along your way? Grabbing coffee along your way? Grabbing coffee along your way?',
          'Annual Pakage': 'Annual Pakage',
          'Gold Pakage': 'Gold Pakage',
          'Add Product': 'Add Product',
          'Product has been added Successfully':
              'Product has been added Successfully',
          'Service Name': 'Service Name',
          'Service Cost': 'Service Cost',
          'Service Details': 'Service Details',
          'Select Delivery Available first': 'Select Delivery Available first',
          'By Appointment': 'By Appointment',
          'Select Business': 'Select Business',
          'Add Service': 'Add Service',
          'Product Name': 'Product Name',
          'Product Price': 'Product Price',
          'Rate and Reviews': 'Rate and Reviews',
          'Product Details': 'Product Details',
          'Product image 1': 'Product image 1',
          'Product image 2': 'Product image 2',
          'Product image 3': 'Product image 3',
          'Write your skill here': 'Write your skill here',
          'Discussion Forum': 'Discussion Forum',
          'Search here': 'Search here',
          'Add new Discussion Post': 'Add new Discussion Post',
          'Add new discussion post': 'Add new discussion post',
          'Write something here': 'Write something here',
          'Add Pictures': 'Add Pictures',
          'Please select Business first': 'Please select Business first',
          'Select Industry': 'Select Industry',
          'Your listing updated Successfully':
              'Your listing updated Successfully',
          'Category': 'Category',
          'Business': 'Business',
          'Publish Now': 'Publish Now',
          'Publish': 'Publish',
          'Empty': 'Empty',
          'Please enter password': 'Please enter password',
          'Enter your mobile number': 'Enter your mobile number',
          'Edit': 'Edit',
          'Delete': 'Delete',
          'Choose the best subscription package for your business:':
              'Choose the best subscription package for your business:',
          'See more': 'See more',
          'Service has been Updated Successfully':
              'Service has been Updated Successfully',
          'See less': 'See less',
          'Comments': 'Comments',
          'Please enter email first': 'Please enter email first',
          'Please select product details first':
              'Please select product details first',
          'Camera': 'Camera',
          'Gallary': 'Gallary',
          'Government Directory': 'Government Directory',
          'Business Name': 'Business Name',
          'Contact info': 'Contact info',
          'Business Overview': 'Business Overview',
          'Business Offered': 'Business Offered',
          'Contact': 'Contact',
          'Search service or industry': 'Search service or industry',
          'Most Popular Industries': 'Most Popular Industries',
          'Trending': 'Trending',
          'Password': 'Password',
          'Whats Trending Now?': 'Whats Trending Now?',
          'Most Recent Listings': 'Most Recent Listings',
          'Popular Product': 'Popular Product',
          'Popular Services': 'Popular Services',
          'product': 'product',
          'or Sign in with': 'or Sign in with',
          'service': 'service',
          'data': 'data',
          'RMS Pack & Movers Service': 'RMS Pack & Movers Service',
          'blue area islamabad': 'blue area islamabad',
          '125 reviews': '125 reviews',
          'Call': 'Call',
          ' Sign up ': ' Sign up ',

          'Chat': 'Chat',
          'Department Name': 'Department Name',
          'Business name*': 'Business name*',
          'Business Name*': 'Business Name*',
          'Business Description*': 'Business Description*',
          'Business email': 'Business email',
          'Cell number': 'Cell number',
          'Landline number': 'Landline number',
          'WhatsApp number': 'WhatsApp number',
          'City': 'City',
          'Physical store* / Virtual store*':
              'Physical store* / Virtual store*',
          'Timings': 'Timings',
          'Monday ': 'Monday ',
          'Tuesday ': 'Tuesday ',
          'Wednesday ': 'Wednesday ',
          'Thursday ': 'Thursday ',
          'Friday ': 'Friday ',
          'Saturday ': 'Saturday ',
          'Sunday ': 'Sunday ',
          'keywords': 'keywords',
          'Hear About': 'Hear About',
          'Phone number fields should not be empty':
              'Phone number fields should not be empty',
          'Select Image': 'Select Image',
          'SUBMIT': 'SUBMIT',
          'City* / Area**': 'City* / Area**',
          'Website URL': 'Website URL',
          'Number of Employs': 'Number of Employs',
          'FaceBook URL': 'FaceBook URL',
          'Instagram URL': 'Instagram URL',
          'Twitter URL': 'Twitter URL',
          'Youtube URl': 'Youtube URl',
          'Service Area': 'Service Area',
          'Delivery Available': 'Delivery Available',
          'Reset': 'Reset',
          'PickUp': 'PickUp',
          'By Appointment': 'By Appointment',
          'Business Registration': 'Business Registration',
          'Create your': 'Create your',
          ' Business ': ' Business ',
          'Account free and get Register your business':
              'Account free and get Register your business',
          'salc': 'salc',
          'Select Package': 'Select Package',
          'Yes': 'Yes',
          'No': 'No',
          'Booking': 'Booking',
          'Sub Category': 'Sub Category',
          'Select time': 'Select time',
          'Contact Us': 'Contact Us',
          'Call Us': 'Call Us',
          'Email Us': 'Email Us',
          ' with businesses directly using our Message system. ':
              ' with businesses directly using our Message system. ',
          'Chat with Us': 'Chat with Us',
          'Quick Contact': 'Quick Contact',
          'First Name': 'First Name',
          'Email': 'Email',
          'Phone': 'Phone',
          'SEND': 'SEND',
          'Confirm': 'Confirm',
          'Free': 'Free',
          ' your ': ' your ',
          'password ': 'password ',
          'Let\'s finally..': 'Let\'s finally..',
          'New Password': 'New Password',
          'Confirm Password': 'Confirm Password',
          'OTP': 'OTP',
          'Forgot': 'Forgot',
          'so Try again..': 'so Try again..',
          'Add New Business': 'Add New Business',
          'Profile': 'Profile',
          'How it works': 'How it works',
          'Customer care': 'Customer Care',
          'Logout': 'Logout',
          'How it Works': 'How it Works',
          'Filter': 'Filter',
          'Verified': 'Verified',
          'Open Now': 'Open Now',
          'Top Rated': 'Top Rated',
          'Send Message': 'Send Message',
          'Enter message here': 'Enter message here',
          '3.30PM': '3.30PM',
          'Say something …': 'Say something …',
          'Phone verification': 'Phone verification',
          'Otp code': 'Otp code',
          'Arrive at your destination in the smoothest ride possible, by sailing through real-time trip planning to payment with a few clicks. We\'re never more than 5 minutes away with pick-up stations closer from and to your home, office or anywhere in between. Grabbing coffee along your way?':
              'Arrive at your destination in the smoothest ride possible, by sailing through real-time trip planning to payment with a few clicks. We\'re never more than 5 minutes away with pick-up stations closer from and to your home, office or anywhere in between. Grabbing coffee along your way?',
          'Aaban Motors Cars': 'Aaban Motors Cars',
          '30 min': '30 min',
          'Automobile > Bikes': 'Automobile > Bikes',
          '25 Likes': '25 Likes',
          '12 Comments': '12 Comments',
          'Update': 'Update',
          'Edit Profile': 'Edit Profile',
          'Previous password': 'Previous password',
          'Mobile No': 'Mobile No',
          'My Activity': 'My Activity',
          'My Interest': 'My Interest',
          'More': 'More',
          'Rate this Business': 'Rate this Business',
          'Address': 'Address',
          'Social media': 'Social media',
          'Social Media': 'Social Media',
          'Business Description': 'Business Description',
          'Popular products': 'Popular products',
          'Popular Products': 'Popular Products',
          'jsnx': 'jsnx',
          'View All': 'View All',
          'Hours & Services may differ': 'Hours & Services may differ',
          'Monday - Saturday': 'Monday - Saturday',
          'Products': 'Products',
          'Rs ': 'Rs ',
          'Services': 'Services',
          'Phone number fields should not is empty':
              'Phone number fields should not is empty',
          'Details': 'Details',
          'Rating this item': 'Rating this item',
          'Rating and Reviews': 'Rating and Reviews',
          'Search': 'Search',
          'SIGN IN': 'SIGN IN',
          'Email or phone': 'Email or phone',
          'Email or Phone': 'Email or Phone',
          'Password': 'Password',
          'Forgot Password ?': 'Forgot Password ?',
          'Forgot Password': 'Forgot Password',
          'Or Sign in with': 'Or Sign in with',
          'Don\'t have an account ? ': 'Don\'t have an account ? ',
          'Sign Up': 'Sign Up',
          ' account ': ' account ',
          'for FREE right now': 'for FREE right now',
          'Last Name': 'Last Name',
          '03 061234567': '03 061234567',
          'CREATE ACCOUNT': 'CREATE ACCOUNT',
          'Or Sign Up with': 'Or Sign Up with',
          'Already have an account ?': 'Already have an account ?',
          ' Sign In ': ' Sign In ',
          'Sign in': 'Sign in',
          'Choose your language': 'Choose your language',
          'اپنی زبان کا انتخاب کریں': 'اپنی زبان کا انتخاب کریں',
          'ENGLISH': 'ENGLISH',
          'اردو': 'اردو',
          'Dial Box': 'Dial Box',
          'Search for anything,anywhere in Pakistan':
              'Search for anything,anywhere in Pakistan',
          'List your business on Dialboxx to gain leads and to showcase your products, services & business information online':
              'List your business on Dialboxx to gain leads and to showcase your products, services & business information online',
          'Rate': 'Rate',
          'Select Terms and Condition box': 'Select Terms and Condition box',
          'Add up to 3 Images': 'Add up to 3 Images',
          'Service Starting Cost': 'Service Starting Cost',
        },

        //...................................................//
        'de_DE': {
          'Home': 'گھر',
          'Discussion': 'بحث',
          'Listings': 'فہرستیں',
          'Please select industry': 'براہ کرم انڈسٹری منتخب کریں',
          'Message': 'پیغام',
          'Your listing has been sent for review. You will be notified once approved & online!':
              'آپ کی لسٹنگ جائزہ کے لیے بھیج دی گئی ہے۔ ایک بار منظوری اور آن لائن آپ کو مطلع کیا جائے گا!',
          'Government': 'حکومت',
          'Your account has been suspended . Please contact customer support':
              'آپ کا اکاؤنٹ معطل کر دیا گیا ہے۔ براے مہربانی کسٹمر سپورٹ سے رابطہ کریں',
          'Can\'t get gurrent location': 'گورینٹ لوکیشن نہیں مل سکتی',
          'Please make sure you enable GPS and try again':
              'براہ کرم یقینی بنائیں کہ آپ GPS کو فعال کرتے ہیں اور دوبارہ کوشش کریں',
          'Ok': 'ٹھیک ہے',
          'Alert': 'الرٹ',
          'Package Benefits': 'پیکیج کے فوائد',
          'Success': 'کامیابی',
          'my-widget-key': 'میری ویجیٹ کی چابی',
          'Advertise': 'اشتہار دینا',
          'Please verify your account': 'براہ کرم اپنے اکاؤنٹ کی تصدیق کریں',
          'For': 'کے لیے',
          'Product has been added Successfully':
              'پروڈکٹ کامیابی کے ساتھ شامل کر دیا گیا ہے',
          'Advertising': 'تشہیر',
          'Skills': 'ہنر',
          'View All ': 'سب دیکھیں',
          'kindly contact us for further information ':
              'مزید معلومات کے لیے ہم سے رابطہ کریں ',
          'advertise@dailboxx.pk': 'dailboxx.pk کی تشہیر کریں',
          'Notifications': 'اطلاعات',
          'View Business': 'کاروبار دیکھیں',
          'We\'re never more than 5 minutes away with pick-up stations closer from and to your home, office or anywhere in between.':
              'ہم آپ کے گھر ، دفتر یا درمیان میں کہیں بھی پک اپ اسٹیشنوں کے ساتھ 5 منٹ سے زیادہ دور نہیں ہیں',
          '15 June at 02:05 am': '15 جون صبح 02:05 بجے۔',
          'Settings': 'ترتیبات',
          'Change Password': 'پاس ورڈ تبدیل کریں',
          'Terms & Conditions': 'شرائط و ضوابط',
          'Packages': 'پیکجز',
          'Accomplishments': 'کارنامے',
          'Privacy Policy': 'رازداری کی پالیسی',
          'Version': 'ورژن',
          'Register your business with dialboxx and go online today! Help potential buyers get in touch with you using Dialboxx search engine.':
              'اپنے کاروبار کو ڈائل باکس کے ساتھ رجسٹر کریں اور آج ہی آن لائن ہوں! ممکنہ خریداروں کو ڈائل باکس سرچ انجن کا استعمال کرتے ہوئے آپ سے رابطہ کرنے میں مدد کریں',
          '1.0.0': '1.0.0',
          'Service has been added Successfully':
              'سروس کامیابی کے ساتھ شامل کر دی گئی ہے',
          'Skip': 'چھوڑ دو',
          'Activities': 'سرگرمیاں',
          'Information': 'معلومات',
          'All Comments': 'تمام تبصرے',
          'Let\'s do your new habit': 'آئیے اپنی نئی عادت بنائیں',
          'Verification Code': 'تصدیقی کوڈ',
          'Register your bussiness with dialboxx to gain visibility in the marketplace.':
              'مارکیٹ میں مرئیت حاصل کرنے کے لیے اپنے کاروبار کو ڈائل باکس کے ساتھ رجسٹر کریں.',
          'NEXT': 'اگلے',
          'SIGN UP AS': 'بطور سائن اپ کریں',
          'Business Cell Number*': 'بزنس سیل نمبر*',
          'Business Industry': 'کاروباری صنعت',
          'Please enter phone number first': 'براہ کرم پہلے فون نمبر درج کریں',
          'Industries': 'صنعتیں',
          'New Password': 'نیا پاس ورڈ',
          'Experience': 'تجربہ',
          'Donʼt have an account ? ': 'کیا آپ کا اکاؤنٹ نہیں ہے؟',
          'Add': 'شامل کریں',
          'It’s okay to be tired. Try to take some deep breaths when you have a quick minute to yourself. Remember you are worth it! Being kind to others is just as important as being kind to yourself. ':
              'تھک جانا ٹھیک ہے۔ جب آپ اپنے آپ کو ایک تیز وقت دیں تو کچھ گہری سانس لینے کی کوشش کریں۔ یاد رکھیں کہ آپ اس کے قابل ہیں! دوسروں کے ساتھ مہربان ہونا اتنا ہی اہم ہے جتنا اپنے آپ پر مہربان ہونا',
          'Feeling quite overwhelmed today. Wish I had more time to myself.':
              'آج کافی مغلوب ہو رہا ہوں۔ کاش میرے پاس زیادہ وقت ہوتا',
          'INDUSTRY': 'صنعت',
          'CATEGORIES': 'اقسام',
          'Sign in': 'سائن ان',
          'Register your bussiness with dialboxx to gain visibility in the marketplace. Showcase your bussiness information.':
              'مارکیٹ میں مرئیت حاصل کرنے کے لیے اپنے کاروبار کو ڈائل باکس کے ساتھ رجسٹر کریں۔ اپنی کاروباری معلومات دکھائیں.',
          'BUSSINES OWNER': 'کاروبار کا مالک',
          'USER': 'صارف',
          'Please enter otp code': 'براہ کرم او ٹی پی کوڈ درج کریں',
          'Add Business': 'کاروبار شامل کریں',
          'Register your bussiness with dialbox to gain visibility in the marketplace. Showcase your bussiness information, products + Services helping you increase your revenue by bringing you closer to your potential clients.':
              'مارکیٹ میں مرئیت حاصل کرنے کے لیے اپنے کاروبار کو ڈائل باکس سے رجسٹر کریں۔ اپنی کاروباری معلومات ، پروڈکٹس + سروسز دکھائیں جو آپ کو اپنے ممکنہ گاہکوں کے قریب لا کر اپنی آمدنی بڑھانے میں مدد کرتی ہیں.',
          'Choose your plan today and \n1st MONTH FREE':
              'آج ہی اپنا منصوبہ منتخب کریں اور 1 n1 مہینہ مفت',
          'Basic Package': 'بنیادی پیکیج',
          '1,000': '1,000',
          'Please select Category': 'براہ کرم زمرہ منتخب کریں',
          'Education': 'تعلیم',
          'City :': 'شہر:',
          'Rate and Reviews': 'شرح اور جائزے',
          'Please enter message': 'براہ کرم پیغام درج کریں',
          'PKR': 'پی کے آر',
          'My Listings': 'میری فہرستیں',
          'Add Experience': 'تجربہ شامل کریں',
          'Service has been Updated Successfully':
              'سروس کو کامیابی سے اپ ڈیٹ کر دیا گیا ہے',
          'Per Month': 'فی مہینہ',
          'Select business address first': 'پہلے کاروباری پتہ منتخب کریں',
          '2,500 PKR': '2500 روپے',
          'Free': 'مفت',
          'FAQs': 'عمومی سوالات',
          'Report': 'رپورٹ',
          'Sunday :': 'اتوار : ',
          'Select Industry first': 'پہلے انڈسٹری منتخب کریں',
          'Annual Package': 'سالانہ پیکیج',
          'Select how did you hear about us?':
              'منتخب کریں کہ آپ نے ہمارے بارے میں کیسے سنا؟',
          '24,000': '24,000 روپے',
          '30,000 PKR': '30,000 روپے',
          'Send Report': 'رپورٹ بھیجیں',
          'Physical Location/Virtual*': 'جسمانی مقام/مجازی*',
          'Report has been submitted': 'رپورٹ پیش کر دی گئی ہے',
          'Gold Package': 'گولڈ پیکیج',
          'I agree to Dialboxx Terms & Conditions':
              'میں ڈائل باکس کی شرائط و ضوابط سے اتفاق کرتا ہوں',
          'Rate Product': 'مصنوعات کی درجہ بندی کریں',
          '25,000': '25,000 روپے',
          'Update Business': 'اپ ڈیٹ بزنس',
          'Delivery Available*': 'ڈلیوری دستیاب ہے*',
          '33,000 PKR': '33,000 روپے',
          'Your listing updated Successfully':
              'آپ کی لسٹنگ کامیابی سے اپ ڈیٹ ہوئی',
          'PLANS Benefits': 'منصوبوں کے فوائد',
          'Basic Pakage': 'بنیادی پیکیج',
          'We\'re never more than 5 minutes away with pick-up stations closer from and to your home, office or anywhere in between. Grabbing coffee along your way? Grabbing coffee along your way? Grabbing coffee along your way?':
              ' ہم آپ کے گھر ، دفتر یا درمیان میں کہیں بھی پک اپ اسٹیشنوں کے ساتھ 5 منٹ سے زیادہ دور نہیں ہیں۔ اپنے راستے میں کافی پکڑ رہے ہو؟ اپنے راستے میں کافی پکڑ رہے ہو؟ اپنے راستے میں کافی پکڑ رہے ہو؟',
          'Annual Pakage': 'سالانہ پیکیج',
          'Add accomplishments': 'کارنامے شامل کریں',
          'Categories': 'اقسام',
          'Gold Pakage': 'گولڈ پیکیج',
          'Please enter feed back': 'براہ کرم فیڈ بیک درج کریں',
          'Add Product': 'پروڈکٹ شامل کریں',
          'Please select service first': 'براہ کرم پہلے سروس منتخب کریں',
          'Select Physical store* / Virtual store* first':
              'پہلے فزیکل اسٹور* / ورچوئل اسٹور* منتخب کریں',
          'Service Name': 'سروس کا نام',
          'Service Cost': 'سروس لاگت',
          ' on Dialboxx to gain leads and to showcase your products, services & business information online.':
              'ڈائل باکس پر لیڈز حاصل کرنے اور اپنی مصنوعات ، خدمات اور کاروباری معلومات آن لائن دکھانے کے لیے',
          'Categories > business': 'زمرہ جات> کاروبار',
          'Hi , there ': 'ہیلو ، وہاں',
          'Recent Listings': 'حالیہ فہرستیں',
          'for FREE today': 'آج کے لئے مفت',
          'Service Details': 'سروس کی تفصیلات',
          'Select Delivery Available first':
              'پہلے ڈیلیوری دستیاب کو منتخب کریں',
          'Add business name first': 'پہلے کاروباری نام شامل کریں',
          'Select Business': 'کاروبار منتخب کریں',
          'Write your degree type': 'اپنی ڈگری کی قسم لکھیں',
          'Add Service': 'سروس شامل کریں',
          'Booking Available*': 'بکنگ دستیاب ہے*',
          'Product Name': 'پروڈکٹ کا نام',
          'Please select product price first':
              'براہ کرم پہلے مصنوعات کی قیمت منتخب کریں',
          'Update': 'اپ ڈیٹ',
          'Monday - Sunday': 'پیر - اتوار۔',
          'Urdu': 'اردو',
          'Friday :': 'جمعہ : ',
          'Search for service, product or business':
              'سروس ، پروڈکٹ یا کاروبار تلاش کریں',
          'Product Price': 'مصنوعات کی قیمت',
          'Create Account': 'اکاؤنٹ بنائیں',
          'Product Details': 'مصنوعات کی تفصیلات',
          'Register your business with Dialboxx to gain visibility in the market-place.Showcase your business information products + service .... ':
              'اپنے کاروبار کو ڈائل باکس کے ساتھ رجسٹر کریں تاکہ مارکیٹ میں نظر آ سکے۔ اپنے کاروباری معلومات کی مصنوعات + سروس دکھائیں',
          'Product image 1': 'مصنوعات کی تصویر 1۔',
          'Please select product details first':
              'براہ کرم پہلے مصنوعات کی تفصیلات منتخب کریں',
          'Product image 2': 'پروڈکٹ امیج 2',
          'Rate your experience': 'اپنے تجربے کی درجہ بندی کریں',
          'Hey! How’s it all going?': 'ارے! یہ سب کیسے چل رہا ہے؟',
          'Product image 3': 'پروڈکٹ امیج 3',
          'Use Db discussion forum ': 'ڈی بی ڈسکشن فورم استعمال کریں',
          'Discussion Forum': 'ڈسکشن فورم',
          'It’s been an okay day… Lots of School work':
              'یہ ایک اچھا دن رہا ہے… اسکول کا بہت کام',
          ' to connect with likeminded people in our community.':
              'ہماری کمیونٹی کے ہم خیال لوگوں سے رابطہ قائم کرنے کے لیے',
          'Please select image': 'براہ کرم تصویر منتخب کریں',
          'Update Product': 'مصنوعات کو اپ ڈیٹ کریں',
          'Search here': 'یہاں تلاش کریں',
          'Thursday:': 'جمعرات : ',
          'Upload Picture': 'تصویر اپ لوڈ کریں',
          'Rating & Reviews': 'درجہ بندی اور جائزے',
          'Write your Volunteering here': 'اپنی رضاکارانہ خدمات یہاں لکھیں',
          'Add new Discussion Post': 'نئی بحث پوسٹ شامل کریں',
          'Add new discussion post': 'نئی بحث پوسٹ شامل کریں',
          'Write something here': 'یہاں کچھ لکھیں',
          'Update Volunteering': 'رضاکارانہ اپ ڈیٹ کریں',
          'Add Pictures': 'تصاویر شامل کریں',
          'Update accomplishments': 'کارنامے اپ ڈیٹ کریں',
          'Select Industry': 'انڈسٹری منتخب کریں',
          'Take Away/Pick up': 'اٹھاو/اٹھاو',
          'Enter your mobile number': 'اپنا موبائل نمبر درج کیجئے',
          'Category': 'قسم',
          'Business': 'کاروبار',
          'Wednesday :':' بدھ : ',
          'Publish Now': 'ابھی شائع کریں',
          'Publish': 'شائع کریں',
          'Photos': 'تصاویر',
          'Empty': 'خالی',
          'Trending': 'ٹرینڈنگ',
          'Number verification': 'نمبر کی تصدیق',
          'Edit': 'ترمیم',
          'Delete': 'حذف کریں',
          'Please enter last name': 'براہ کرم آخری نام درج کریں',
          'By Appointment': 'تقرری کے ذریعے',
          'Choose the best subscription package for your business:':
              'اپنے کاروبار کے لیے سبسکرپشن کا بہترین پیکیج منتخب کریں',
          'See more': 'دیکھیں مزید',
          'Rate your Experience here': 'اپنے تجربے کی درجہ بندی یہاں کریں',
          'Volunteering': 'رضاکارانہ کام',
          'Add Education': 'تعلیم شامل کریں',
          'Update Experience': 'تجربہ اپ ڈیٹ کریں',
          'See less': 'کم دیکھیں',
          'Mobile No*': 'موبائل نمبر*',
          'Rate Service': 'سروس کی شرح',
          'Password': 'پاس ورڈ',
          'Please enter first name': 'براہ کرم پہلا نام درج کریں',
          'Business City(s) : ': 'بزنس سٹی:',
          'Comments': 'تبصرے',
          'Verify your account by entering 4 digit code you receive from Dialboxx':
              'ڈائل باکس سے موصول ہونے والے 4 ہندسوں کا کوڈ درج کرکے اپنے اکاؤنٹ کی تصدیق کریں',
          'Camera': 'کیمرہ',
          'Gallary': 'گیلری',
          'All Likes': 'تمام پسندیدگی',
          'Government Directory': 'گورنمنٹ ڈائریکٹری',
          'Business Name': 'کاروبار کا نام',
          'Write your position here': 'اپنی پوزیشن یہاں لکھیں',
          'Please add your questions': 'براہ کرم اپنے سوالات شامل کریں',
          'Please confirm Terms and Condition':
              'براہ کرم شرائط و ضوابط کی تصدیق کریں',
          'Contact info': 'رابطہ کی معلومات',
          'Please enter text': 'براہ کرم متن درج کریں',
          'Please rate to Driver': 'براہ کرم ڈرائیور کی درجہ بندی کریں',
          'Business Overview': 'کاروباری جائزہ',
          'Write your skills here': 'اپنی مہارت یہاں لکھیں',
          'Update Education': 'تعلیم کو اپ ڈیٹ کریں',
          'Business Offered': 'کاروبار کی پیشکش',
          'Please enter email or password':
              'براہ کرم ای میل یا پاس ورڈ درج کریں',
          'Contact': 'رابطہ کریں',
          'Saturday :': 'ہفتہ : ',
          'Department Name': 'محکمہ نام',
          'Please enter password first': 'براہ کرم پہلے پاس ورڈ درج کریں',
          'Hello brother': 'ہیلو بھائی',
          'form and submit listing. Once approved, you can start listing products & services.':
              'فارم بنائیں اور لسٹنگ جمع کروائیں۔ منظوری کے بعد ، آپ مصنوعات اور خدمات کی فہرست شروع کر سکتے ہیں',
          'Search service or industry': 'سروس یا صنعت تلاش کریں',
          'Most Popular Industries': 'سب سے زیادہ مشہور صنعتیں',
          'Whats Trending Now?': 'اب کیا ٹرینڈ ہو رہا ہے؟',
          'Most Recent Listings': 'حالیہ فہرستیں',
          'Password didn\'t match': 'پاس ورڈ مماثل نہیں تھا',
          'Popular Product': 'مشہور پروڈکٹ',
          'Popular Services': 'مقبول خدمات',
          'Search for anything, anywhere in Pakistan.':
              'پاکستان میں کہیں بھی کچھ بھی تلاش کریں',
          'product': 'مصنوعات',
          'service': 'سروس',
          ' Privacy Policy': 'رازداری کی پالیسی',
          'You can start listing your businesses after\n registration.':
              'آپ رجسٹریشن کے بعد اپنے کاروبار کی فہرست شروع کر سکتے ہیں',
          'Get in touch': 'رابطے میں رہنا',
          'data': 'ڈیٹا',
          'View Details': 'تفصیلات دیکھیں',
          'Add Volunteering': 'رضاکارانہ خدمات شامل کریں',
          'RMS Pack & Movers Service': 'آر ایم ایس پیک اینڈ موورز سروس',
          'blue area islamabad': 'بلیو ایریا اسلام آباد',
          '125 reviews': '125 جائزے',
          'Select Delivery Available first':
              'پہلے ڈیلیوری دستیاب کو منتخب کریں',
          'Call': 'کال کریں',
          'Chat': 'چیٹ',
          'Tuesday :': ' منگل : ',
          'Business name*': '*کاروبار کا نام',
          'Business Name*': '*کاروبار کا نام',
          'Business Description*': 'کاروباری تفصیل*',
          'Business email': 'کاروباری ای میل',
          'Cell number': 'سیل نمبر',
          'Landline number': 'لینڈلائن نمبر',
          'WhatsApp number': 'واٹس ایپ نمبر',
          'Service Areas': 'سروس ایریاز',
          'City': 'شہر',
          'Physical store* / Virtual store*': 'فزیکل سٹور* / ورچوئل سٹور*',
          'Timings': 'اوقات',
          'Monday ': 'پیر ',
          'Write your time duration': 'اپنے وقت کی مدت لکھیں',
          'Tuesday ': 'منگل ',
          'Wednesday ': 'بدھ ',
          'Please select Business first': 'براہ کرم پہلے بزنس منتخب کریں',
          'Thursday ': 'جمعرات ',
          'Friday ': 'جمعہ ',
          'Time Duration': 'وقت کی مدت',
          'Select package first': 'پہلے پیکیج منتخب کریں',
          'Please select minimum one image first':
              'براہ کرم پہلے کم از کم ایک تصویر منتخب کریں',
          'Saturday ': 'ہفتہ ',
          'Write your School name': 'اپنے سکول کا نام لکھیں',
          'Sunday ': 'اتوار',
          'keywords': 'مطلوبہ الفاظ',
          'Hear About': 'کے بارے میں سنا',
          'Please type message to receiver':
              'براہ کرم وصول کنندہ کو پیغام ٹائپ کریں',
          'Select Image': 'تصویر منتخب کریں',
          'SUBMIT': 'جمع کرائیں',
          'City* / Area**': 'شہر* / علاقہ **',
          'Terms ': 'شرائط',
          'List your business': 'اپنے کاروبار کی فہرست بنائیں',
          'Website URL': 'ویب سائٹ کا پتا',
          'Number of Employs': 'ملازمین کی تعداد',
          'Write your company name': 'اپنی کمپنی کا نام لکھیں',
          'FaceBook URL': 'فیس بک یو آر ایل',
          'Submit': 'جمع کرائیں',
          'Please enter email first': 'براہ کرم پہلے ای میل درج کریں',
          'Instagram URL': 'انسٹاگرام یو آر ایل',
          'Otp fields should not is empty':
              'او ٹی پی فیلڈز خالی نہیں ہونی چاہئیں',
          'Twitter URL': 'ٹویٹر یو آر ایل',
          'Please enter password': 'براہ کرم پاس ورڈ درج کریں',
          'Youtube URl': 'یوٹیوب یو آر ایل',
          'Service Area': 'سروس ایریا',
          'Register your business with dialboxx to gain visibility in the marketplace.':
              'مارکیٹ میں مرئیت حاصل کرنے کے لیے اپنے کاروبار کو ڈائل باکس کے ساتھ رجسٹر کریں',
          'Select City first': 'پہلے شہر منتخب کریں',
          'Delivery Available': 'ڈلیوری دستیاب ہے',
          'Please fields should not is empty':
              'براہ کرم فیلڈز خالی نہیں ہونے چاہئیں',
          'PickUp': 'پک اپ',
          'By Appointment': 'تقرری کے ذریعے',
          'Business Registration': 'کاروبار کا اندراج',
          'Create your': 'اپنا بنائیں',
          'Question?': 'سوال؟',
          ' Business ': ' کاروبار ',
          'Instagram Link': 'انسٹاگرام لنک',
          'Account free and get Register your business':
              'اکاؤنٹ فری اور اپنے کاروبار کو رجسٹر کروائیں',
          'salc': 'سالک',
          'Department Overview': 'محکمہ کا جائزہ',
          'Select Package': 'پیکیج منتخب کریں',
          'Write your accomplishments here': 'اپنے کارنامے یہاں لکھیں',
          'Yes': 'جی ہاں',
          'Please select product name first':
              'براہ کرم پہلے پروڈکٹ کا نام منتخب کریں',
          'No': 'نہیں',
          'Booking': 'بکنگ',
          'Sub Category': 'ذیلی زمرہ',
          'Select time': 'وقت منتخب کریں',
          'Contact Us': 'ہم سے رابطہ کریں',
          'Call Us': 'ہمیں بلائیں',
          'Email Us': 'ہمیں ای میل کریں',
          'Chat with Us': 'ہمارے ساتھ چیٹ کریں',
          'Quick Contact': 'فوری رابطہ',
          'First Name': 'پہلا نام',
          'Add cell number first': 'پہلے سیل نمبر شامل کریں',
          'Email': 'ای میل',
          'Phone': 'فون',
          ' with businesses directly using our Message system. ':
              'ہمارے میسج سسٹم کو براہ راست استعمال کرنے والے کاروباروں کے ساتھ',
          'SEND': 'بھیجیں',
          'Please add your questions first':
              'براہ کرم پہلے اپنے سوالات شامل کریں',
          'Reset': 'ری سیٹ کریں',
          'Confirm': 'تصدیق کریں',
          'Add FAQs': 'عمومی سوالات شامل کریں',
          ' your ': ' آپ کا ',
          'Write your Education here': 'اپنی تعلیم یہاں لکھیں',
          'password ': 'پاس ورڈ ',
          'Let\'s finally..': 'چلو آخر میں ..',
          'New Password': 'نیا پاس ورڈ',
          'Confirm Password': 'پاس ورڈ کی تصدیق کریں',
          'OTP': 'OTP',
          'Forgot': 'بھول',
          'so Try again..': 'تو دوبارہ کوشش کریں ..',
          'Add New Business': 'نیا کاروبار شامل کریں',
          'Profile': 'پروفائل',
          'How it works': 'یہ کیسے کام کرتا ہے',
          'Customer care': 'صارفین کی سہولت',
          'Logout': 'لاگ آوٹ',
          'Website link': 'ویب سائٹ کا لنک',
          'Fill in the': 'میں بھریں',
          'How it Works': 'یہ کیسے کام کرتا ہے',
          'Filter': 'فلٹر',
          ' business ': 'کاروبار ',
          'YouTube Link': 'یوٹیوب لنک',
          'Verified': 'تصدیق شدہ',
          'Facebook Link': 'فیس بک لنک',
          'Open Now': 'ابھی کھولیں',
          'Write your skill here': 'اپنی مہارت یہاں لکھیں',
          'Enter your email or number below and we will send you a link to reset your password.':
              'نیچے اپنا ای میل یا نمبر درج کریں اور ہم آپ کو اپنا پاس ورڈ دوبارہ ترتیب دینے کے لیے ایک لنک بھیجیں گے',
          'Top Rated': 'سب سے اوپر ریٹیڈ',
          'Send Message': 'پیغام بھیجیں',
          'Enter message here': 'یہاں پیغام درج کریں',
          '3.30PM': '3.30PM',
          'Say something …': '… کچھ بولیں',
          'Phone verification': 'فون کی تصدیق',
          'Otp code': 'او ٹی پی کوڈ',
          'Arrive at your destination in the smoothest ride possible, by sailing through real-time trip planning to payment with a few clicks. We\'re never more than 5 minutes away with pick-up stations closer from and to your home, office or anywhere in between. Grabbing coffee along your way?':
              'چند کلکس کے ذریعے ادائیگی کے لیے ریئل ٹائم ٹرپ پلاننگ کے ذریعے جہاز رانی کر کے ممکنہ تیز ترین سواری میں اپنی منزل پر پہنچیں۔ ہم آپ کے گھر ، دفتر یا درمیان میں کہیں بھی پک اپ اسٹیشنوں کے ساتھ 5 منٹ سے زیادہ دور نہیں ہیں۔ اپنے راستے میں کافی پکڑ رہے ہو؟',
          'Aaban Motors Cars': 'آبان موٹرز کاریں',
          '30 min': '30 منٹ',
          'Automobile > Bikes': 'آٹوموبائل> بائیک',
          '25 Likes': '25 پسند',
          '12 Comments': '12 تبصرے',
          'Update': 'اپ ڈیٹ',
          'Edit Profile': 'پروفائل میں ترمیم کریں',
          'Previous password': 'پچھلا پاس ورڈ',
          'Mobile No': 'موبائل نمبر',
          'My Activity': 'میری سرگرمی۔',
          'My Interest': 'میری دلچسپی',
          'More': 'مزید',
          'Rate this Business': 'اس کاروبار کی درجہ بندی کریں',
          'Address': 'پتہ',
          'Monday :': ' پیر : ',
          'Wednesday': ': بدھ',
          'Social media': 'سوشل میڈیا',
          'Social Media': 'سوشل میڈیا',
          'Business Description': 'کاروباری تفصیل',
          'Popular products': 'مقبول مصنوعات',
          'Popular Products': 'مقبول مصنوعات',
          'Add Skills': 'ہنر شامل کریں',
          'jsnx': 'jsnx',
          'Type your answer here': 'اپنا جواب یہاں ٹائپ کریں',
          'View All': 'سب دیکھیں',
          'Hours & Services may differ': 'اوقات اور خدمات مختلف ہو سکتی ہیں',
          'Monday - Saturday': 'پیر - ہفتہ',
          'Products': 'مصنوعات',
          'Rs ': 'Rs ',
          'Services': 'خدمات',
          'Business Details': 'کاروباری تفصیلات',
          'Details': 'تفصیلات',
          'Rating this item': 'اس آئٹم کی درجہ بندی',
          'Rating and Reviews': 'درجہ بندی اور جائزے',
          'Search': 'تلاش کریں',
          'SIGN IN': 'سائن ان',
          'Email or phone': 'ای میل یا فون',
          'Email or Phone': 'ای میل یا فون',
          'Password': 'پاس ورڈ',
          'Forgot Password ?': 'پاسورڈ بھول گے ؟',
          'Forgot Password': 'پاسورڈ بھول گے',
          'Or Sign in with': 'یا کے ساتھ سائن ان کریں',
          'or Sign in with': 'یا کے ساتھ سائن ان کریں',
          'Don\'t have an account ? ': 'کیا آپ کا اکاؤنٹ نہیں ہے؟',
          'Please select city first': 'براہ کرم پہلے شہر کا انتخاب کریں',
          'Sign Up': 'سائن اپ',
          ' account ': 'کھاتہ ',
          'Business Address*': '*کاروباری پتہ',
          'Update Skills': 'مہارت کو اپ ڈیٹ کریں',
          'for FREE right now': 'ابھی مفت کے لیے',
          'Last Name': 'آخری نام',
          ' Sign up ': 'سائن اپ',
          'Phone number fields should not is empty':
              'فون نمبر فیلڈز خالی نہیں ہونی چاہئیں',
          'CREATE ACCOUNT': 'اکاؤنٹ بنائیں',
          'Or Sign Up with': 'یا کے ساتھ سائن اپ کریں',
          'Or Sign up with': 'یا کے ساتھ سائن اپ کریں',
          'Already have an account ?': 'پہلے سے ہی ایک اکاؤنٹ ہے؟',
          ' Sign In ': ' سائن ان ',
          'Choose your language': 'اپنی زبان کا انتخاب کریں',
          'Phone number fields should not be empty':
              'فون نمبر کے فیلڈز خالی نہیں ہونے چاہئیں',
          'ENGLISH': 'انگریزی',
          'اردو': 'اردو',
          'Dial Box': 'ڈائل باکس',
          'Search for anything,anywhere in Pakistan':
              'ٮ﮹اکستان مٮ﮵ں کہٮ﮵ں ٮ﮳ھیٮ﮳ھی ٮ﮴لاش کرٮ﮵ں ',
          'Rate': 'شرح',
          'Select Terms and Condition box': 'شرائط و ضوابط کا خانہ منتخب کریں',
          'Add up to 3 Images': 'تصاویر تک شامل کریں۔3',
          'Service Starting Cost': 'سروس شروع کرنے کی لاگت',
          'Select City': 'شہر منتخب کریں',
        }
      };
}
